basetreinamento = [
("Vendaval causa estragos na Grande Florianópolis ","Cotidiano"),
("Defesa Civil alerta para tempestades em todas as regiões de SC ","Cotidiano"),
("Vítima de acidente em Blumenau, Christian amava os avós e queria trabalhar com TI ","Cotidiano"),
("Fabian Londero presenteia Bonner e Renata com canecas e trajes típicos da Oktoberfest ","Cotidiano"),
("Previsão indica risco de temporais com granizo e ventos de até 90 km/h em SC ","Cotidiano"),
("Defesa Civil alerta para tempestades em três regiões de SC ","Cotidiano"),
("Identificadas as quatro vítimas da mesma família que morreram em acidente na BR-282 ","Cotidiano"),
("Catarinense está em coma após agressão em rua na Austrália ","Cotidiano"),
("Morte de Norberto Cabral: médico colocou Joinville no cenário internacional da pesquisa do AVC ","Cotidiano"),
("Bombeiros são acionados para combater incêndio no Shopping Park Europeu em Blumenau ","Cotidiano"),
("Identificados adolescentes que morreram em acidente na Vila Itoupava, em Blumenau ","Cotidiano"),
("Família busca por irmãs desaparecidas em Joinville ","Cotidiano"),
("Grave acidente deixa dois adolescentes de 17 anos mortos em Blumenau ","Cotidiano"),
("Acidente entre dois carros deixa quatro mortos na BR-282, em Águas Mornas ","Cotidiano"),
("Criança de 8 anos morre após cair de prédio de 18 andares em Piçarras, no Litoral Norte de SC ","Cotidiano"),
("Gabrielly, vítima de acidente em Blumenau, sonhava ser maquiadora ","Cotidiano"),
("Elevador do novo aeroporto de Florianópolis sofre queda ","Cotidiano"),
("Seis pessoas morrem em acidentes de trânsito em SC em menos de 24h ","Cotidiano"),
("Epagri/Ciram alerta para risco de temporais com granizo em SC entre sábado e domingo ","Cotidiano"),
("Quatro conselheiros tutelares eleitos em Joinville são cassados após denúncias ","Cotidiano"),
("Ciclista morre após ser atropelada por caminhão no túnel sob a BR-101 em Itapema ","Cotidiano"),
("VÍDEO: câmera flagra acidente entre dois caminhões na BR-470 em Blumenau ","Cotidiano"),
("Resumo do dia: acidente de trânsito mata médico Norberto Cabral e SC vai contratar 2 mil servidores da Educação ","Cotidiano"),
("Homem que morreu em acidente na SC-421, entre Blumenau e Pomerode, é identificado ","Cotidiano"),
("Motorista morre carbonizado após cair em ribanceira na Serra Dona Francisca em Joinville ","Cotidiano"),
("Começa apuração para conhecer os novos conselheiros tutelares de Joinville ","Cotidiano"),
("Caminhoneiro morre em acidente envolvendo três carretas na divisa entre SC e PR ","Cotidiano"),
("Duas pessoas morrem após carro invadir calçada na avenida Santos Dumont em Joinville ","Cotidiano"),
("Fotos mostram como ficou a cozinha que pegou fogo em shopping de Blumenau ","Cotidiano"),
("Mulher de 52 anos morre após bater o carro na BR-470, em Ibirama ","Cotidiano"),
("Cidades de SC são atingidas por temporal com granizo; previsão mantém alerta ","Cotidiano"),
("Dois adultos e um bebê morrem em acidente na Rodovia do Arroz em Joinville ","Cotidiano"),
("Fabian Londero faz a primeira participação no Jornal Nacional ","Cotidiano"),
("Novo RG passa a ser emitido a partir da próxima segunda-feira em Santa Catarina ","Cotidiano"),
("SC tem alertas para rajadas de vento e temporais com granizo entre terça e quarta-feira ","Cotidiano"),
("Elevador do novo aeroporto de Florianópolis cai após problema técnico ","Cotidiano"),
("Bombeiros são chamados para controlar incêndio no bairro Bom Retiro, em Blumenau ","Cotidiano"),
("Saiba como fazer o pedido de renovação da CNH no novo site do Detran-SC ","Cotidiano"),
("Conheça os 15 novos conselheiros tutelares eleitos em Joinville ","Cotidiano"),
("Oktoberfest ganha destaque no JN com Fabian Londero na bancada ","Cotidiano"),
("VÍDEO: saiba como chegar até o novo aeroporto de Florianópolis ","Cotidiano"),
("Em 2020 o número de feriados prolongados será o dobro de 2019 ","Cotidiano"),
("Corpo encontrado no Rio Itajaí-Açú em Blumenau é identificado pelo Instituto Médico Legal ","Cotidiano"),
("Nuvem prateleira: entenda o fenômeno registrado antes de temporal em Laguna, no Litoral Sul ","Cotidiano"),
("Vídeo: motorista morre após acidente na SC-421, entre Blumenau e Pomerode ","Cotidiano"),
("Carro cai em valeta na zona Norte de Joinville ","Cotidiano"),
("Amor em dose tripla: Jonas, Fábio e Gilmar rompem tabus em um relacionamento a três ","Cotidiano"),
("Saiba o que pode acontecer na primeira vez de uma mulher ","Cotidiano"),
("Pedido de renovação da CNH pode ser feito pela internet em SC ","Cotidiano"),
("Caminhão tomba na SC-401 e complica trânsito no sentido Centro, em Florianópolis ","Cotidiano"),
("Varejo on-line fatura R 32 bilhões na Black Friday e cresce 236 diz Ebit","Economia"),
("Consumo da China eleva preço e deve fazer da carne artigo de luxo no Brasil","Economia"),
("Caixa diz que saque de R 500 do FGTS será devolvido ao fundo em um dia útil","Economia"),
("Em crise indústria automotiva alemã anuncia 50 mil demissões em 2019","Economia"),
("Enel recebe multa de R 13 milhões por queda de luz que afetou 427 mil clientes","Economia"),
("Só 5 dos produtos em destaque em site em outubro entram na Black Friday","Economia"),
("Setor público tem superávit primário de R 94 bi em outubro","Economia"),
("Cliente pesquisa na internet antes de comprar na rua durante Black Friday - Redes de varejo chegam a dar desconto superiores a 40 em seção de celulares","Economia"),
("Após inadimplência bater quase 30 OAB prevê queda - Projeção para 2019 é de 22","Economia"),
("Brasileiros vendem água feita com umidade do ar da Amazônia por 70 euros","Economia"),
("Apps de comida estendem promoção para garantir entrega na Black Friday","Economia"),
("Saque imediato do FGTS tira dinheiro do fundo por até 6 meses","Economia"),
("Safra de café deverá atingir 667 milhões de sacas em 2020 estima Rabobank","Economia"),
("Déficit comercial de novembro vira superávit após governo corrigir erro de quase US 4 bi","Economia"),
("BC vende US 1 bi à vista e dólar recua para R 4216","Economia"),
("Petrobras corta investimentos em 10 e reforça foco no pré-sal","Economia"),
("Brasil é o país de maior crescimento no Dia do Solteiro diz AliExpress","Economia"),
("Trabalhador poderá ter de bancar custos de processos contra o INSS","Economia"),
("Só 13 dos produtos aumentam de preço antes da Black Friday","Economia"),
("Governo limita juro do cheque especial a 8 ao mês mas libera cobrança de tarifa","Economia"),
("Dólar bate recorde pelo 3º pregão seguido e vai a R 4258","Economia"),
("Novo modelo de cesta básica pode reduzir subsídios em R 12 bilhões","Economia"),
("Bolsonaro libera R 22 bilhões em emendas após ameaça","Economia"),
("Mega-Sena acumula de novo e pode pagar R 50 milhões na quarta-feira","Economia"),
("Atividade fabril da China retorna inesperadamente ao crescimento em novembro","Economia"),
("5 dicas para sua loja vender mais no Natal","Economia"),
("Oportunidade: cresce o número de microfranquias no RS","Economia"),
("Contas de luz terão bandeira tarifária amarela em dezembro","Economia"),
("Faturamento do comércio salta 20 durante a Black Friday","Economia"),
("Games lideram descontos na Black Friday","Economia"),
("Preço da gasolina sobe nos postos mostra levantamento da ANP","Economia"),
("“Pensei mil vezes em fechar”, diz empreendedor que hoje comemora sucesso ","Economia"),
("Programa da Celesc dá 50 de desconto em eletrodomésticos; saiba como comprar ","Economia"),
("Ministério da Agricultura suspende venda de 33 marcas de azeite de oliva no Brasil ","Economia"),
("Companhia vai operar voos de baixo custo entre Florianópolis e Santiago a partir de novembro ","Economia"),
("Saiba como fica o desconto do INSS no salário após a reforma da Previdência ","Economia"),
("FGTS: agências da Caixa abrem em horário especial nesta sexta, sábado e segunda-feira ","Economia"),
("Prefeitura de Blumenau abre inscrições para vagas com salário de até R 5,7 mil ","Economia"),
("FGTS: Caixa antecipa calendário de saques de até R 500 ","Economia"),
("Cerimônia de inauguração do aeroporto de Florianópolis é marcada por shows e presença de autoridades ","Economia"),
("IBGE abre 60 vagas de nível médio para Censo 2020 em Santa Catarina ","Economia"),
("Prefeito de Florianópolis sanciona lei que proíbe venda e uso de agrotóxicos na cidade ","Economia"),
("FGTS: Caixa abrirá agências mais cedo nesta sexta e no sábado para saques de até R 500 ","Economia"),
("Tire suas dúvidas sobre o saque do FGTS anunciado pelo governo federal ","Economia"),
("Joinville, Chapecó e São José estão entre as 20 cidades que mais geraram empregos no país ","Economia"),
("Conta de água ficará mais barata para metade dos usuários em SC, aponta agência reguladora ","Economia"),
("Quando a franquia não lucra, a culpa é do franqueado ou do franqueador? ","Economia"),
("Caixa anuncia redução de juros do crédito imobiliário ","Economia"),
("Startup deve fechar o ano com faturamento de R 3 milhões ","Economia"),
("Agências do Sine em Santa Catarina têm 2,9 mil vagas de emprego disponíveis ","Economia"),
("Risoto de linguiça Blumenau: um esquenta para a Oktoberfest ","Economia"),
("Entenda o que muda no seu negócio com a Lei da Liberdade Econômica ","Economia"),
("Confira vagas abertas nas lojas do novo terminal do aeroporto de Florianópolis ","Economia"),
("Gênio' 'exemplo' e 'gratidão': o que os famosos disseram sobre Gugu","Entretenimento"),
("Sabrina Sato mostra look estiloso da filha Zoe para banho de piscina: 'Amor'","Entretenimento"),
("Final alternativo de “Game of Thrones” foi gravado confirma ator","Entretenimento"),
("Andressa Suita responde seguidora e levanta possibilidade de 3º filho. Entenda!","Entretenimento"),
("Filhos de Kaká levam alianças no casamento do pai com Carol Dias. Vídeo!","Entretenimento"),
("Vingadores: Ultimato’: Uniforme da Capitã Marvel seria o mesmo de seu filme solo","Entretenimento"),
("Chris Hemsworth está proibido de levar mais um Mjolnir para casa","Entretenimento"),
("Game of Thrones’: Showrunners revelam como a saga literária irá terminar","Entretenimento"),
("Carol Dias escolhe vestido de noiva princesa em casamento com Kaká. Aos detalhes","Entretenimento"),
("‘Vis a Vis: El Oasis’: Criador afirma que derivado será o verdadeiro final da série","Entretenimento"),
("Pokémon Sword & Shield ganha bichinhos de pelúcia oficiais","Entretenimento"),
("Shawn Mendes cancela show em São Paulo neste sábado (30); entenda","Entretenimento"),
("‘Harley Quinn’ briga com o Coringa no trailer do próximo episódio da animação; Assista!","Entretenimento"),
("Entre Facas e Segredos’: Chris Evans é interrogado em novo clipe do suspense","Entretenimento"),
("Anitta grava clipe da música ‘Meu mel’ em parceria com Melim","Entretenimento"),
("Catarinense Bettina, a milionária, reaparece em novo vídeo e pede desculpas ","Entretenimento"),
("Confirmados os preços dos chopes na Oktoberfest 2019 ","Entretenimento"),
("Oktoberfest 2019: programação, ingressos e tudo mais que você precisa saber sobre a festa ","Entretenimento"),
("Caso Jully: MC Gui tem shows cancelados após ser acusado de bullying com criança ","Entretenimento"),
("Festival em Florianópolis deve reunir 15 mil pessoas no Parque de Coqueiros no final de semana ","Entretenimento"),
("Fabian no JN: a duas semanas da participação no Jornal Nacional, apresentador relata expectativa ","Entretenimento"),
("Confira o cardápio completo e preços da Oktoberfest 2019 ","Entretenimento"),
("Caminhoneiro morre em acidente entre três carretas próximo da divisa entre SC e PR ","Entretenimento"),
("Por que a vagina fica mais ou menos dilatada? ","Entretenimento"),
("Oktoberfest 2019: veja quanto custam e como comprar os ingressos da festa ","Entretenimento"),
("Morre o ator e diretor Jorge Fernando ","Entretenimento"),
("É normal que a mulher fique lubrificada demais durante a transa? ","Entretenimento"),
("Após 26 anos, Sérgio Chapelin se despede do Globo Repórter nesta sexta-feira ","Entretenimento"),
("Oktoberfest 2019: como funciona o Oktober Karte, cartão de pagamento usado na festa ","Entretenimento"),
("VÍDEO: Fabian Londero convida catarinenses a assistir ao JN deste sábado ","Entretenimento"),
("PopStar: Jakson Follman surpreende jurados e público no 1° dia ","Entretenimento"),
("Realeza da Oktoberfest 2020 é escolhida na última noite de festa em Blumenau ","Entretenimento"),
("É possível engravidar fazendo sexo anal? ","Entretenimento"),
("FOTOS: desfile da Oktoberfest leva milhares de pessoas ao Centro de Blumenau ","Entretenimento"),
("Oktoberfest 2019: primeiro sábado de festa registra público 40,2 maior do que em 2018 ","Entretenimento"),
("Aprenda a fazer o Tropical Gin, drinque queridinho do verão ","Entretenimento"),
("Stammitsch reúne 30 mil pessoas na via gastronômica de Joinville ","Entretenimento"),
("Oktoberfest 2019 terá sete desfiles: veja as datas, horários e como participar ","Entretenimento"),
("Confira algumas novidades deste ano das festas de outubro do Vale do Itajaí ","Entretenimento"),
("O que causa a diminuição do desejo sexual nas mulheres? ","Entretenimento"),
("Quantas vezes na semana é normal um casal fazer sexo? ","Entretenimento"),
("VÍDEO: NSC lança o hit É linda a nossa Santa Catarina para a Oktoberfest 2019 ","Entretenimento"),
("ATL Day ocorre no próximo fim de semana na Beira-Mar Norte de Florianópolis ","Entretenimento"),
("Oktoberfest 2019: programação de shows e outras atrações em Blumenau ","Entretenimento"),
("ALT Day ocorre no próximo fim de semana na Beira-Mar Norte de Florianópolis ","Entretenimento"),
("Confira 25 séries imperdíveis para ver na Netflix ","Entretenimento"),
("Oktoberfest 2019: VoxxClub e outros 25 shows neste sábado; veja a programação ","Entretenimento"),
("Única companhia de balé com bailarinos cegos do mundo se apresenta em Joinville ","Entretenimento"),
("Oktoberfest: Conheça as 10 finalistas do concurso para a realeza da festa de 2020 ","Entretenimento"),
("81ª Festa das Flores é lançada oficialmente em Joinville; confira as atrações ","Entretenimento"),
("Fotos: desfile da Oktoberfest lota o Centro de Blumenau ","Entretenimento"),
("Ceará abre o placar mas Athletico empata no fim e embola briga contra o rebaixamento","Esporte"),
("No Grande Círculo Renan recorda Geração de Prata e vislumbra dupla Leal e Lucarelli em Tóquio","Esporte"),
("Corinthians posta imagem de camisa usada por Luan em 2012 e agita torcida nas redes sociais","Esporte"),
("Argel Fucks diz que Ceará massacrou e credita empate ao goleiro Santos: Fez milagre","Esporte"),
("Qual elenco vale mais? Veja comparativo entre os milionários Palmeiras e Flamengo","Esporte"),
("GP de Abu Dhabi: Lewis Hamilton sobra conquista última pole position de 2019 e quebra jejum","Esporte"),
("Diego Hypólito anuncia sua aposentadoria da ginástica","Esporte"),
("Atacante do Newell's comemora gol contra o River imitando Gabigol do Fla","Esporte"),
("Brasileiro faz 3 Benfica goleia e se consolida na liderança em Portuga","Esporte"),
("Avaí chega a 15 jogos sem vencer no Brasileirão um a menos que pior sequência do time","Esporte"),
("Diretor da Chape fala em reconstruir e estabilizar o clube","Esporte"),
("Rodada desta quarta-feira decretou o fim de 2019 para o futebol catarinense","Esporte"),
("Avaí perde para o Corinthians por 3 a 0 pelo Brasileirão 2019","Esporte"),
("Técnico falou sobre causas da queda da Chapecoense","Esporte"),
("Corredor amputado completa oitava corrida na Meia Maratona de Floripa","Esporte"),
("Conheça a jovem catarinense que surpreendeu na disputa dos Jogos Escolares da Juventude","Esporte"),
("Com garotos em campo Avaí está pronto para encarar o Fluminense","Esporte"),
("Léo Gamalho deixa o futuro no Criciúma em aberto: Não sei o que vai acontecer","Esporte"),
("Figueirense: tchau 2019!","Esporte"),
("Multado Matheus Barbosa não deve jogar mais pelo Avaí em 2019","Esporte"),
("Multado Matheus Barbosa não deve jogar mais pelo Avaí em 2019","Esporte"),
("Jorge Jesus é homenageado com título de cidadão honorário do Rio","Esporte"),
("Sede da Olimpíada de 2024 Paris se irrita com acordo entre COI e Airbnb","Esporte"),
("Chefe da federação russa de atletismo é suspenso por obstruir investigação","Esporte"),
("Maior ‘quebra-pau’ da história da NBA completa 15 anos","Esporte"),
("Pierre Gasly o piloto mais feliz (e sortudo) do GP Brasil de Fórmula 1","Esporte"),
("Verstappen vence GP do Brasil de Fórmula 1 pela primeira vez","Esporte"),
("Doria diz que renovação com a Fórmula 1 pode acontecer ainda este ano","Esporte"),
("Figueirense volta aos treinos e lateral-esquerdo se despede dos companheiros de elenco ","Esporte"),
("CBF tira mais três pontos do Figueirense, que cai para 20 ","Esporte"),
("STJD rejeita pedido de Honigman para Figueirense desistir da Série B ","Esporte"),
("Acompanhe Avaí x Vasco pela Série A do Campeonato Brasileiro ","Esporte"),
("Pintado é o novo técnico do Figueirense para a sequência da Série B ","Esporte"),
("Avaí x Palmeiras: escalações, onde assistir e ingressos de jogo do Brasileirão ","Esporte"),
("Goleiro Bruno tem contrato rescindido após 45 minutos em campo ","Esporte"),
("Família de catarinense morto em incêndio na sede do Flamengo confirma acordo com clube ","Esporte"),
("Gustavo Kuerten: A internet é uma fonte de desabafo gigantesca ","Esporte"),
("Avaí perde para o CSA em jogo com erro do VAR ","Esporte"),
("De virada, Figueirense vence o América-MG por 2 a 1 ","Esporte"),
("Luciano Hang planeja entrada no futebol com arena de R 15 milhões ","Esporte"),
("Avaí sofre goleada do Grêmio pelo Brasileirão 2019 ","Esporte"),
("Figueirense vence o Paraná e sobe duas posições ","Esporte"),
("Figueirense estuda rompimento com a Topper e pode ter novo fornecedor esportivo em 2020 ","Esporte"),
("Criciúma busca empate em 2 a 2 diante do Figueirense no Scarpelli ","Esporte"),
("Desfalcado, Figueirense embarca para jogo fora de casa contra o Atlético-GO ","Esporte"),
("Em entrevista, Cláudio Honigman fala em terrorismo de atletas do Figueirense ","Esporte"),
("Policia conduz filho de Flordelis e apreende bens","Policia"),
("Homem que gravou vídeo dando tapas nas filhas se apresenta à Policia","Policia"),
("Homem é encontrado morto na zona Leste de Joinville","Policia"),
("Deputada Flordelis diz ter sido vítima de ameaças e extorsão","Policia"),
("Flordelis participa de reconstituição da morte do marido na região metropolitana do Rio","Policia"),
("Justiça decreta prisão preventiva contra filhos de Flordelis","Policia"),
("Filha de Flordelis fez proposta a irmão para matar o pai diz jornal","Policia"),
("Advogado diz que marido de Flordelis foi envenenado","Policia"),
("PRF apreende 600 kg de camarão contrabandeado na BR-282 no Oeste de SC","Policia"),
("Policia acredita que padrasto teria matado menina de 12 anos em Joinville","Policia"),
("Presos vão fazer placas e tachões para as rodovias estaduais de Santa Catarina","Policia"),
("Menina de 12 anos e padrasto são encontrados mortos na zona Leste de Joinville","Policia"),
("​Corpo de homem é encontrado no bairro Profipo em Joinville ​","Policia"),
("​Ciclista é encontrado morto na Serra Dona Francisca","Policia"),
("Homem que espancou filha e enteada em vídeo é preso pela Policia","Policia"),
("PF indicia mais 25 pessoas dentro da operação Alcatraz","Policia"),
("Após indiciamento Julio Garcia é recebido com apoio de colegas na Alesc","Policia"),
("As lições de 2019 na Câmara de Vereadores de Florianópolis","Policia"),
("Placas já avisam: ponte Hercílio Luz somente para ônibus","Policia"),
("Tour vai relembrar a Novembrada em Florianópolis","Policia"),
("Instalação de parque eólico na Serra Catarinense gera protesto de ambientalistas","Policia"),
("PM tem surto e faz disparos dentro de companhia de Policia na Bahia e depois mata ex-namorada","Policia"),
("Policial militar é assassinado a tiros dentro de casa em Paracambi","Policia"),
("Homem é preso pela Policia Civil após esfaquear primo em Nova Andradina","Policia"),
("Acidente com três veículos deixa uma pessoa morta e quatro feridos na BR 280","Policia"),
("Policia Federal e FN fazem operação e prendem barraconense com moto roubada","Policia"),
("Condutora tenta desviar de buraco na rodovia perde o controle e tomba em rio","Policia"),
("Estupros aumentam 55 em um mês na cidade de Guarulhos","Policia"),
("Quadrilha que aplicou golpes de R 2 milhões em idosos em bancos de Guarulhos é presa","Policia"),
("PF apreende mais de 40 Kg de cocaína e prende 5 no fim de semana em Guarulhos","Policia"),
("PM prende três criminosos que mantiveram duas pessoas como reféns no Presidente Dutra","Policia"),
("GCM presta apoio à Assistência Social durante abordagem","Policia"),
("Com chave de roda imitando uma arma homem tenta roubar posto na Ponte Grande","Policia"),
("Após briga homem mata a ex-companheira e é detido no Jardim Paraíso","Policia"),
("Acusados de roubar carga em frente ao Shopping Bonsucesso são presos","Policia"),
("Suspeito de sumir com o ouro de Guarulhos tem câncer avançado","Policia"),
("Com empurrão de outro carro veículo sem bateria é furtado no Picanço","Policia"),
("Médico Norberto Cabral morre em acidente na Serra Dona Francisca, em Joinville ","Policia"),
("Mulher que abandonou bebê recém-nascido em Florianópolis é identificada pela Policia ","Policia"),
("Menina de 13 anos é resgatada após ser mantida em cativeiro por dois meses, em Palhoça ","Policia"),
("Irmãs que estavam desaparecidas voltam para casa em Joinville ","Policia"),
("Família é presa suspeita de usar carne de cachorro para fazer linguiça no Espírito Santo ","Policia"),
("Irmã planejou local e função dos envolvidos em execução de jovem em Gaspar, diz delegado ","Policia"),
("PMRv atende grave acidente de trânsito no acesso ao novo aeroporto de Florianópolis ","Policia"),
("Casal é assassinado dentro de casa, em Nova Trento, e suspeito é preso ","Policia"),
("Homem fica desacordado após briga no primeiro dia de Oktoberfest em Blumenau ","Policia"),
("Motorista de transporte por aplicativo é morto em Joinville ","Policia"),
("Bebê com menos de 10 dias é encontrado em caixa de papelão no Centro de Florianópolis ","Policia"),
("Mulher é vítima de feminicídio em São Francisco do Sul, diz Policia ","Policia"),
("Catarinense agredido na Austrália morre após 10 dias internado no hospital ","Policia"),
("Homem de 50 anos é morto a tiros na zona Sul de Joinville ","Policia"),
("Morre Marco Tebaldi, ex-prefeito de Joinville ","Politica"),
("Como será a primeira visita de Bolsonaro como presidente a Florianópolis ","Politica"),
("Justiça cancela pensão especial de filha de ex-deputado que recebia benefício desde 1970 em SC ","Politica"),
("Ex-prefeito Marco Tebaldi será sepultado em Joinville no fim da tarde de segunda-feira ","Politica"),
("Familiares e amigos se despedem do ex-prefeito Marco Tebaldi em Joinville ","Politica"),
("Eleições 2020: fim das coligações eleitorais e outras mudanças ","Politica"),
("Visita do presidente Jair Bolsonaro movimenta academia da PRF, em Florianópolis ","Politica"),
("Foi guerreiro até o final da doença, diz filho de Marco Tebaldi durante velório ","Politica"),
("Fim da estabilidade no funcionalismo deve pautar debates sobre reforma administrativa no Congresso ","Politica"),
("Assessor do PT que ficou milionário em bolão volta a ganhar na Mega-Sena ","Politica"),
("Eleições 2020 em Santa Catarina começam a se desenhar ","Politica"),
("Prefeitura decreta luto oficial de cinco dias pela morte do ex-prefeito de Joinville Marco Tebaldi ","Politica"),
("Após cortejo, Marco Tebaldi é sepultado em Joinville ","Politica"),
("Eduardo Bolsonaro ironiza sigla LGBT em camiseta ","Politica"),
("Lideranças de Joinville lamentam a morte de Marco Tebaldi ","Politica"),
("Não há uma prova de que eu seja sócio oculto, diz Julio Garcia sobre indiciamento na Alcatraz ","Politica"),
("Bolsonaro tem nome citado em planilha apreendida em ação que apura candidaturas laranjas do PSL, diz jornal ","Politica"),
("Vice-presidente Hamilton Mourão visita empresa e faz palestra no Norte de SC ","Politica"),
("Advogada de Bolsonaro diz que presidente negocia com cinco partidos ","Politica"),
("Operação Alcatraz: deputado Julio Garcia é apontado como sócio oculto de empresa ","Politica"),
("Mais de 15 milhões de pessoas ainda precisam fazer biometria ou não poderão votar em 2020","Politica"),
("Escritório comercial do governo em Jerusalém funcionará em 'coworking' e terá 3 empregados","Politica"),
("Caso Mariellle: Aras diz não ver 'indícios mínimos' de que Bolsonaro tenha feito obstrução","Politica"),
("Presidente e o filho Carlos foram alvos de pedido de investigação por acessarem áudio de ","Politica"),
("Câmara do MP critica proposta que muda regra do repasse de emendas parlamentares","Politica"),
("Texto, aprovado na Câmara e sob análise do Senado, cria duas modalidades de repasse e transfere, de órgãos federais para de estados e municípios, a fiscalização do uso da verba","Politica"),
("Gilmar Mendes revoga decisão que paralisou investigação sobre Flávio Bolsonaro","Politica"),
("Ministério Público do Rio poderá retomar investigação sobre suspeita de que Flávio praticava 'rachadinha' na época em que era deputado estadual.","Politica"),
("Bolsonaro acusa Leonardo DiCaprio e WWF de financiarem queimadas na Amazônia","Politica"),
("Declarações do presidente repercutiram fora do país. WWF disse que Bolsonaro divulga 'inverdades'. Ator americano não se pronunciou","Politica"),
("Submetidas a 'hackers' por 5 dias, urnas eletrônicas têm só duas falhas superficiais, informa TSE","Politica"),
("TSE recebeu nesta semana 25 acadêmicos, estudantes e peritos para Teste Público de Segurança. Grupo mudou dados superficiais, mas não conseguiu alterar nome de candidato nem de eleitor.","Politica"),
("Rodrigo Maia e Tabata Amaral debatem nova agenda social da Câmara com Gerson Camarotti","Politica"),
("GloboNews Politica mostra conversa do jornalista com a deputada e o presidente da Câmara, nesta sexta-feira (29), às 21h30, na GloboNews.","Politica"),
("Governo prevê arrecadar R 6,4 bilhões em 2020 com renegociação da dívida ativa","Politica"),
("Haverá duas modalidades de parcelamento: transação por adesão, destinada a devedores com dívidas até R 15 milhões, e transação individual, para débitos de maior por","Politica"),
("STF libera repasse de dados sigilosos ao MPF; BC mira agora cartão de crédito","Politica"),
("'Cultura tem que estar de acordo com a maioria da população', diz Bolsonaro sobre chefe da Fundação Palmares","Politica"),
("Novo chefe da fundação afirmou nas redes sociais que escravidão foi 'benéfica para os descendentes'. Bolsonaro disse que deu 'carta branca' para quem indicou o chefe da fundação.","Politica"),
("Governo edita MP para conceder auxílio a pescadores de municípios atingidos por óleo","Politica"),
("Auxílio emergencial é de R 1.996, e o pagamento será feito em duas parcelas iguais a municípios relacionados até esta sexta (29) no site do Ibama.","Politica"),
("Com Receita autorizada a repassar dados sigilosos ao MP, cai liminar obtida por Flávio Bolsonaro","Politica"),
("Liminar que havia paralisado todos os procedimentos baseados em informações sigilosas da Receita foi derrubada após julgamento desta quinta em que STF autorizou compartilhamento.","Politica"),
("Relator na Câmara propõe proibir que motociclista trafegue entre carros em movimento","Politica"),
("Texto estabelece que motos só poderão passar entre duas faixas quando veículos estiverem parados. Sugestão consta de proj","Politica"),
("Bolsonaro telefona para presidente eleito do Uruguai e o convida para visitar o Brasil","Politica"),
("Informação foi divulgada pelo Itamaraty. Representante da direita uruguaia, Luis Lacalle Pou apostou em discurso de enxugamento de ga","Politica"),
("Comissão denuncia Bolsonaro ao Tribunal Penal Internacional por supostamente promover ataques contra os povos indígenas","Politica"),
("Segundo jurista, Bolsonaro pode ser investigado pelos crimes de 'incitação ao genocídio e de lesa-humanidade - caracterizados pela reiteração de atos contra os","Politica"),
("Deputados também aprovaram convites ao presidente da Petrobrás, aos diretores-gerais da PF e da ANP e ao comandante da Marinha; pedidos de convocação foram convertidos em convite.","Politica"),
("Ministério da Saude realiza pesquisa durante fiscalização de trânsito em Cuiabá","Saude"),
("Unidade de Saude tem formigas e remédios vencidos: ‘estamos adoecendo’ diz funcionária","Saude"),
("Sarampo enfraquece sistema imunológico contra outras doenças","Saude"),
("Luxemburgo retira câncer de pele. Saiba quando pinta é perigosa","Saude"),
("Soluços em bebês podem ter papel no desenvolvimento do cérebro indica estudo","Saude"),
("Brasil reforça vacinação de sarampo e febre amarela nas fronteiras","Saude"),
("Sarampo mata o dobro que o ebola na República Democrática do Congo","Saude"),
("Pesquisadores descobrem “parente” do chikungunya","Saude"),
("Vacinas para a alergia: perguntas e respostas","Saude"),
("Acesso de vias venosas centrais permanentes","Saude"),
("Após cartinha ao Papai Noel menino ganha aparelho de audição","Saude"),
("Sífilis a doença evitável e de tratamento barato que mata um número crescente de bebês no Brasil","Saude"),
("O sonambulismo segundo a neurociência","Saude"),
("Poluição atmosférica causa 7 milhões de mortes por ano","Saude"),
("Jovens de 20 a 29 anos vão a postos de Saude se vacinar contra sarampo","Saude"),
("Dia D da vacinação contra o sarampo acontece neste sábado","Saude"),
("De dor a tumor: as complicações causadas pelo dente do siso","Saude"),
("5 coisas que provocam desequilíbrios hormonais sem você saber","Saude"),
("Cistite depois de ter relações sexuais: por quê?","Saude"),
("São Paulo tem 25 criadouros de dengue por residência","Saude"),

]
